### ISSUE TITLE
Update to use go modules.

### ISSUE THREAD

**Issue by cjsaylor** [cjsaylor/jrnl#13]
Update the dependencies to use go modules and remove `dep` artifacts and documentation.

**Comment by justinpage** [comment]
I would like to help out with this. 

Would be a good learning experience since go modules are new to me.

**Comment by cjsaylor** [comment]
@justinpage "Go" for it. :smile:

**Comment by cjsaylor** [comment]
@justinpage Let me know if you'd like some assistance.

**Comment by justinpage** [comment]
@justinpage Thank you! Plan is to work on this during the weekend.
